apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-connector2
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aci-connector
    spec:
      containers:
      - name: aci-connector
        image: microsoft/aci-connector-k8s:canary
        imagePullPolicy: Always
        env:
        - name: AZURE_CLIENT_ID
          value: <tenant-id>
        - name: AZURE_CLIENT_KEY
          value: <app-id>
        - name: AZURE_TENANT_ID
          value: <tenant-id>
        - name: AZURE_SUBSCRIPTION_ID
          value: <subscription-id>
        - name: ACI_RESOURCE_GROUP
          value: antchu-aci-temp