---
kind: Service
apiVersion: v1
metadata:
  name: webstore
  labels:
   app: webstore
spec:
  selector:
    app: webstore
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webstore-deployment
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: webstore
    spec:
      containers:
      - name: webstore
        image: torosent/webstore:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: ORDER_SERVICE
          value: "http://orderservice/api/order"
        - name: STATUS_SERVICE
          value: "http://statusservice/api/status"        
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: printingservice-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: printingservice
    spec:
      containers:
      - name: printingservice
        image: torosent/printingservice:1.0.0
        imagePullPolicy: Always
        env:
          - name: SBConnectionString
            valueFrom:
              secretKeyRef:
                name: stickerstore
                key: SBConnectionString
          - name: StorageConnectionString
            valueFrom:
              secretKeyRef:
                name: stickerstore
                key: StorageConnectionString
---
kind: Service
apiVersion: v1
metadata:
  name: orderservice
  labels:
   app: orderservice
spec:
  selector:
    app: orderservice
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderservice-deployment
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: torosent/orderservice:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: SBConnectionString
          valueFrom:
            secretKeyRef:
              name: stickerstore
              key: SBConnectionString
---
kind: Service
apiVersion: v1
metadata:
  name: statusservice
  labels:
   app: statusservice
spec:
  selector:
    app: statusservice
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statusservice-deployment
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: statusservice
    spec:
      containers:
      - name: statuservice
        image: torosent/statusservice:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: StorageConnectionString
          valueFrom:
            secretKeyRef:
              name: stickerstore
              key: StorageConnectionString


        