apiVersion: v1
kind: Secret
metadata:
  name: stickerstore
type: Opaque
data:
  SBConnectionString: 
  StorageConnectionString: 



# To prepare secret, we need to encode it to Base64
# echo -n "admin" | base64 or use https://www.base64encode.org/